In [23]:
import numpy as np

a = np.random.randn(3, 3)
b = np.random.randn(3, 3)
a, b

(array([[ 0.26270437,  1.57866975,  0.05380273],
        [ 0.53323702, -0.35146792,  0.31473997],
        [-1.20289969,  0.34484567,  1.4344036 ]]),
 array([[-0.15160629, -2.17539215, -1.06294306],
        [ 0.06411676,  1.42323071, -0.56582343],
        [ 0.73780861, -1.25151014, -0.96975889]]))

In [24]:
# matrix addition
c = []
for i in range(3):
    l = []
    for j in range(3):
        l.append(a[i][j] + b[i][j])
    c.append(l)
c = np.array(c)
print("\nTheir sum")
print(c)
print("Is it correct?")
print(a + b == c)
assert np.array_equal(a + b, c)


Their sum
[[ 0.11109808 -0.5967224  -1.00914033]
 [ 0.59735378  1.0717628  -0.25108346]
 [-0.46509108 -0.90666447  0.46464472]]
Is it correct?
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [25]:
# matrix subtraction
c = []
for i in range(3):
    l = []
    for j in range(3):
        l.append(a[i][j] - b[i][j])
    c.append(l)
c = np.array(c)
print("\nTheir difference")
print(c)
print("Is it correct?")
print(a - b == c)
assert np.array_equal(a - b, c)


Their difference
[[ 0.41431066  3.7540619   1.1167458 ]
 [ 0.46912027 -1.77469863  0.8805634 ]
 [-1.9407083   1.5963558   2.40416249]]
Is it correct?
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [26]:
# matrix multiplication
c = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(len(a)):
    l = []
    for j in range(len(b[0])):
        # l.append(a[i][j] + b[i][j])
        for k in range(len(b)):
                # l.append(a[i][k] * b[k][j])
                c[i][j] += a[i][k] * b[k][j]
c = np.array(c)
print(c.shape)
print(c == a@b)
print(a@b)
print(c)

(3, 3)
[[False False  True]
 [ True  True  True]
 [False  True  True]]
[[ 0.10108767  1.60799158 -1.2246638 ]
 [ 0.12884079 -2.05411983 -0.67315369]
 [ 1.26279287  1.31240284 -0.30753351]]
[[ 0.10108767  1.60799158 -1.2246638 ]
 [ 0.12884079 -2.05411983 -0.67315369]
 [ 1.26279287  1.31240284 -0.30753351]]


In [27]:
# matrix transpose
def transpose(a):
    a_t = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
    for i in range(3):
        for j in range(3):
            a_t[j][i] = a[i][j]
    return np.array(a_t)

print(transpose(a) == a.T)
assert np.array_equal(transpose(a), a.T)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [28]:
# matrix inversion
def inversion(m):    
    m1, m2, m3, m4, m5, m6, m7, m8, m9 = m.flatten()
    determinant = m1*m5*m9 + m4*m8*m3 + m7*m2*m6 - m1*m6*m8 - m3*m5*m7 - m2*m4*m9  
    return np.array([[m5*m9-m6*m8, m3*m8-m2*m9, m2*m6-m3*m5],
                     [m6*m7-m4*m9, m1*m9-m3*m7, m3*m4-m1*m6],
                     [m4*m8-m5*m7, m2*m7-m1*m8, m1*m5-m2*m4]])/determinant

print(inversion(a))
print(np.linalg.inv(a))
print(inversion(a) == np.linalg.inv(a))

[[ 0.30959538  1.13487459 -0.2606292 ]
 [ 0.57781119 -0.22311647  0.02728371]
 [ 0.12071672  1.00535236  0.47202931]]
[[ 0.30959538  1.13487459 -0.2606292 ]
 [ 0.57781119 -0.22311647  0.02728371]
 [ 0.12071672  1.00535236  0.47202931]]
[[ True False  True]
 [ True False  True]
 [False  True False]]


In [29]:
# max element and minimum element
min_elem = 10000000000
max_elem = -1000000000
for r in a:
    for i in r:
        min_elem = min(min_elem, i)
        max_elem = max(max_elem, i)

print(max_elem)
print(max_elem == np.amax(a))
print(min_elem)
print(min_elem == np.amin(a))

1.5786697517156865
True
-1.2028996921022364
True


In [30]:
# max element and minimum element in every row
# min_elem = 10000000000
# max_elem = -1000000000
for r in a:
    min_elem = 10000000000
    max_elem = -1000000000
    for i in r:
        min_elem = min(min_elem, i)
        max_elem = max(max_elem, i)
        print("The max elem in row", r, "is", max_elem)
        print("The min elem in row", r, "is", min_elem)
        print("")

The max elem in row [0.26270437 1.57866975 0.05380273] is 0.26270437255449675
The min elem in row [0.26270437 1.57866975 0.05380273] is 0.26270437255449675

The max elem in row [0.26270437 1.57866975 0.05380273] is 1.5786697517156865
The min elem in row [0.26270437 1.57866975 0.05380273] is 0.26270437255449675

The max elem in row [0.26270437 1.57866975 0.05380273] is 1.5786697517156865
The min elem in row [0.26270437 1.57866975 0.05380273] is 0.053802734461147785

The max elem in row [ 0.53323702 -0.35146792  0.31473997] is 0.533237024938788
The min elem in row [ 0.53323702 -0.35146792  0.31473997] is 0.533237024938788

The max elem in row [ 0.53323702 -0.35146792  0.31473997] is 0.533237024938788
The min elem in row [ 0.53323702 -0.35146792  0.31473997] is -0.3514679174226191

The max elem in row [ 0.53323702 -0.35146792  0.31473997] is 0.533237024938788
The min elem in row [ 0.53323702 -0.35146792  0.31473997] is -0.3514679174226191

The max elem in row [-1.20289969  0.34484567  1.4

In [31]:
# max and min element in every coloumn 
temp = transpose(a)
for r in temp:
    min_elem = 10000000000
    max_elem = -1000000000
    for i in r:
        min_elem = min(min_elem, i)
        max_elem = max(max_elem, i)
        print("The max elem in col", r, "is", max_elem)
        print("The min elem in col", r, "is", min_elem)
        print("")

The max elem in col [ 0.26270437  0.53323702 -1.20289969] is 0.26270437255449675
The min elem in col [ 0.26270437  0.53323702 -1.20289969] is 0.26270437255449675

The max elem in col [ 0.26270437  0.53323702 -1.20289969] is 0.533237024938788
The min elem in col [ 0.26270437  0.53323702 -1.20289969] is 0.26270437255449675

The max elem in col [ 0.26270437  0.53323702 -1.20289969] is 0.533237024938788
The min elem in col [ 0.26270437  0.53323702 -1.20289969] is -1.2028996921022364

The max elem in col [ 1.57866975 -0.35146792  0.34484567] is 1.5786697517156865
The min elem in col [ 1.57866975 -0.35146792  0.34484567] is 1.5786697517156865

The max elem in col [ 1.57866975 -0.35146792  0.34484567] is 1.5786697517156865
The min elem in col [ 1.57866975 -0.35146792  0.34484567] is -0.3514679174226191

The max elem in col [ 1.57866975 -0.35146792  0.34484567] is 1.5786697517156865
The min elem in col [ 1.57866975 -0.35146792  0.34484567] is -0.3514679174226191

The max elem in col [0.0538027

In [32]:
# trace of a matrix
trace = 0
for i in range(len(a)):
    for j in range(len(b)):
        if i == j:
            trace += a[i][j]
print(trace)
print(trace == np.trace(a))

1.3456400571516391
True


In [33]:
# rank of a matrix
print(np.linalg.matrix_rank(a))

3


In [34]:
# eigen values and vectors
print(np.linalg.eig(a))

EigResult(eigenvalues=array([ 1.24355786+0.43274523j,  1.24355786-0.43274523j,
       -1.14147567+0.j        ]), eigenvectors=array([[-0.19315071+0.36411988j, -0.19315071-0.36411988j,
        -0.67823788+0.j        ],
       [-0.19003166+0.17328717j, -0.19003166-0.17328717j,
         0.61688153+0.j        ],
       [-0.87405323+0.j        , -0.87405323-0.j        ,
        -0.39931261+0.j        ]]))


In [35]:
# mean
l = a.flatten()
sum = l.sum()
print(sum)
count = len(l)
print("Mean =", sum / count)
print(sum / count == l.mean())

2.9680355102135714
Mean = 0.32978172335706346
True


In [36]:
# median
l = a.flatten()
l.sort()

if len(l) % 2 == 0:
    m1 = l[len(l) // 2]
    m2 = l[len(l) // 2 - 1]
    median = (m1 + m2) / 2
else:
    median = l[len(l) // 2]
print(median)
print(median == np.median(a))

0.3147399673112526
True


In [37]:
# Mode
l = a.flatten()
frequency = {}
for i in l:
    frequency.setdefault(i, 0)
    frequency[i] += 1

frequent = max(frequency.values())
for i, j in frequency.items():
    if j == frequent:
        mode = i
print(mode)

1.4344036020197615


In [38]:
import math

def mean_of_list(l):
   sum = 0
   for i in range(len(l)):
      sum += l[i]
   return sum / len(l)

l = a.flatten()
mean = mean_of_list(l)
deviation_sum = 0
for i in range(len(l)):
   deviation_sum += (l[i] - mean) ** 2

sd = math.sqrt((deviation_sum) / len(l))
print(sd)
print(np.std(l))
print(sd == np.std(l))

0.7969131561785474
0.7969131561785474
True


In [48]:
# matrix inversion using gauss jordan method
n = 3
A = [[np.random.randint(1, 10) for i in range(n)] for j in range(n)]
print(A)
A_i = np.linalg.inv(A)
print(A_i)

[[6, 3, 6], [6, 7, 2], [6, 1, 7]]
[[-1.95833333  0.625       1.5       ]
 [ 1.25       -0.25       -1.        ]
 [ 1.5        -0.5        -1.        ]]


In [49]:
# This should return eye matrix
print(A_i@A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
# Let's try to write this on our own
n = 5
A = [[np.random.randint(1, 10) for i in range(n)] for j in range(n)]
A = np.array(A)
print(A)
for i in range(len(A)):
    for j in range(len(A)):
        if j < i:
            print(A[i][j], end=" ")
    print("")

[[5 9 9 6 2]
 [2 6 6 8 5]
 [6 3 2 3 2]
 [9 1 4 3 7]
 [4 5 5 7 3]]

2 
6 3 
9 1 4 
4 5 5 7 
