In [1]:
# 1) program to find the largest of three numbers
a, b, c = input("Enter 3 Numbers").split(' ')
if a > b:
    if a > c:
        max = a
    else:
        max = c
else:
    if b > c:
        max = b
    else:
        max = c
print("The max number is", max)

The max number is 3


In [2]:
# 2) counting the number of vowels in a given string
s = input("Enter a string")
l = list(s)
count = 0
for a in l:
    if a == 'a' or a == 'e' or a == 'i' or  a == 'o' or a == 'u':
        count += 1
print("The number of vowels is", count)

The number of vowels is 7


In [3]:
# 3) calculate the factorial of a number
num = input("Give me a whole number")
while int(num) < 0:
    print("This is not a whole number")
    num = input("Give me a whole number")
num = int(num)
l = [1, 1]
for i in range(num + 1):
    if i > 1:
        l.append((i) * l[i - 1])
print("The Factorial of the number is", l[-1])

The Factorial of the number is 6


In [4]:
# 4) finding out if a number is prime or not
import math

num = int(input("Give me a natural number"))
while num < 1:
    print("This is not a natural number")
    num = int(input("Give me a natural number"))
if num == 1:
    print("One is not a prime number")
flag = False
for i in range(2, math.ceil(math.sqrt(num))):
    if num % i == 0:
        flag = True

if not flag:
    print(num, "is a prime number")
else:
    print(num, "is a not prime number")

6 is a not prime number


In [25]:
# 5) matrix addition
import numpy as np

a = np.random.randn(2, 2)
b = np.random.randn(2, 2)
c = []
print("The matrices are")
print("a = ", a)
print(a)
print("b = ", b)
print(b)
for i in range(2):
    l = []
    for j in range(2):
        l.append(a[i][j] + b[i][j])
    c.append(l)
c = np.array(c)
print("\nTheir sum")
print(c)
print("Is it correct?")
print(a + b == c)
assert np.array_equal(a + b, c)

The matrices are
a =  [[ 1.95039685 -0.71830399]
 [ 1.01697071  0.15011751]]
[[ 1.95039685 -0.71830399]
 [ 1.01697071  0.15011751]]
b =  [[ 2.11456562 -0.36291659]
 [ 0.92731299  0.19149319]]
[[ 2.11456562 -0.36291659]
 [ 0.92731299  0.19149319]]

Their sum
[[ 4.06496247 -1.08122057]
 [ 1.9442837   0.3416107 ]]
Is it correct?
[[ True  True]
 [ True  True]]


In [6]:
# 6) linear search 
numbers = list(map(int, input("Give me a list of numbers: ").split(' ')))
num = int(input("Give me a number: "))

index = -1
for i, a in enumerate(numbers):
    if a == num:
        index = i
        break

if index != -1:
    print(f"We have found the number at index {index}")
else:
    print("We have not found the number in the list")

We have found the number at index 4


In [ ]:
# 7) gcd of two numbers
def gcd(x, y):
    while(y):
       x, y = y, x % y
    return abs(x)

a = int(input("Give me a number"))
b = int(input("Give me another number"))
print("The GCD of the two numbers", a, "and", b, "is", gcd(a, b))

The GCD of the two numbers 100 and 10 is 10


In [34]:
# 8) transpose of a matrix
import numpy as np
a = np.random.randn(3, 3)
a_t = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(3):
    for j in range(3):
        a_t[j][i] = a[i][j]
a_t = np.array(a_t)
print("a = ")
print(a, end="\n\n")
print("It's transpose is")
print(a_t, end="\n\n")
print("Is it correct?")
print(a_t == a.T)
assert np.array_equal(a_t, a.T)

a = 
[[-0.06618365 -0.93038158  0.02447197]
 [-0.5685271   0.66336282 -1.8587918 ]
 [ 0.5140374  -0.13337381 -0.99932588]]

It's transpose is
[[-0.06618365 -0.5685271   0.5140374 ]
 [-0.93038158  0.66336282 -0.13337381]
 [ 0.02447197 -1.8587918  -0.99932588]]

Is it correct?
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
